// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiCi2VO0e6DQP_P9c-gz1qRAXtTtYY1g0',
    appId: '1:277056695670:web:605e37b894be8143149e57',
    messagingSenderId: '277056695670',
    projectId: 'flutter-todo-9f027',
    authDomain: 'flutter-todo-9f027.firebaseapp.com',
    storageBucket: 'flutter-todo-9f027.firebasestorage.app',
    measurementId: 'G-84T53523RL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuQa6mdHNtcqCt_AH8iTtTlZ8-ijk96oo',
    appId: '1:277056695670:android:f519e6dafa64e1bd149e57',
    messagingSenderId: '277056695670',
    projectId: 'flutter-todo-9f027',
    storageBucket: 'flutter-todo-9f027.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiCi2VO0e6DQP_P9c-gz1qRAXtTtYY1g0',
    appId: '1:277056695670:web:18aac226acd5e211149e57',
    messagingSenderId: '277056695670',
    projectId: 'flutter-todo-9f027',
    authDomain: 'flutter-todo-9f027.firebaseapp.com',
    storageBucket: 'flutter-todo-9f027.firebasestorage.app',
    measurementId: 'G-1Y8R1TY5VG',
  );
}
